"use client";

import { useState } from "react";
import { Navbar } from "@/components/Navbar";
import { VaultCard } from "@/components/VaultCard";
import { VAULT_META } from "@/lib/constants";
import { useTotalTvl } from "@yo-protocol/react";
import { formatAmount } from "@/lib/utils";
import { Search, Filter } from "lucide-react";

const CATEGORIES = ["All", "Stablecoin", "ETH"];
const RISKS = ["All", "Conservative", "Moderate", "Growth"];

const VAULT_CATEGORY: Record<string, string> = {
  yoUSD: "Stablecoin",
  yoETH: "ETH",
};
const VAULT_RISK: Record<string, string> = {
  yoUSD: "Conservative",
  yoETH: "Moderate",
};

export default function VaultsPage() {
  const [category, setCategory] = useState("All");
  const [risk, setRisk] = useState("All");
  const [search, setSearch] = useState("");

  const { tvl, isLoading: tvlLoading } = useTotalTvl();

  const allVaults = Object.entries(VAULT_META);

  const filtered = allVaults.filter(([id, meta]) => {
    if (category !== "All" && VAULT_CATEGORY[id] !== category) return false;
    if (risk !== "All" && VAULT_RISK[id] !== risk) return false;
    if (
      search &&
      !meta.name.toLowerCase().includes(search.toLowerCase()) &&
      !meta.assetSymbol.toLowerCase().includes(search.toLowerCase())
    )
      return false;
    return true;
  });

  return (
    <>
      <Navbar />
      <main className="pt-20 min-h-screen max-w-7xl mx-auto px-4 sm:px-6 pb-16">
        {/* Header */}
        <div className="mb-8 mt-8">
          <h1 className="text-3xl font-black text-white mb-2">YO Vaults</h1>
          <p className="text-[#6b9e7e]">
            Risk-adjusted, onchain yield — powered by YO Protocol.
            {!tvlLoading && tvl && (
              <span className="text-[#22c55e] font-medium ml-2">
                ${formatAmount((tvl as any)?.totalTvl ?? 0n, 6, 0)} TVL
              </span>
            )}
          </p>
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-3 mb-8">
          {/* Search */}
          <div className="relative flex-1 max-w-sm">
            <Search
              size={15}
              className="absolute left-3 top-1/2 -translate-y-1/2 text-[#6b9e7e]"
            />
            <input
              className="w-full bg-[#0f2d1e] border border-[#1a4a2e] rounded-xl pl-9 pr-4 py-2.5 text-sm text-white placeholder-[#6b9e7e]/60 focus:outline-none focus:border-[#22c55e]/50 transition-colors"
              placeholder="Search vaults..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <Filter size={14} className="text-[#6b9e7e] shrink-0" />
            {/* Category filter */}
            <div className="flex bg-[#0f2d1e] border border-[#1a4a2e] rounded-xl p-1 gap-1">
              {CATEGORIES.map((c) => (
                <button
                  key={c}
                  onClick={() => setCategory(c)}
                  className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-all ${category === c
                    ? "bg-[#22c55e]/15 text-[#22c55e]"
                    : "text-[#6b9e7e] hover:text-white"
                    }`}
                >
                  {c}
                </button>
              ))}
            </div>

            {/* Risk filter */}
            <div className="flex bg-[#0f2d1e] border border-[#1a4a2e] rounded-xl p-1 gap-1">
              {RISKS.map((r) => (
                <button
                  key={r}
                  onClick={() => setRisk(r)}
                  className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-all ${risk === r
                    ? "bg-[#22c55e]/15 text-[#22c55e]"
                    : "text-[#6b9e7e] hover:text-white"
                    }`}
                >
                  {r}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Vault grid */}
        {filtered.length === 0 ? (
          <div className="text-center py-16">
            <div className="text-4xl mb-3">🔍</div>
            <div className="text-[#6b9e7e]">No vaults match your filters</div>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {filtered.map(([vaultId]) => (
              <VaultCard key={vaultId} vaultId={vaultId} />
            ))}
          </div>
        )}

        {/* YO Protocol attribution */}
        <div className="mt-12 rounded-2xl border border-[#1a4a2e] bg-[#0f2d1e] p-6 text-center">
          <div className="text-sm text-[#6b9e7e] mb-2">
            All yields are generated by{" "}
            <strong className="text-white">YO Protocol</strong> — an
            algorithmic, multi-chain yield optimizer that deploys capital to the
            highest risk-adjusted opportunities across DeFi.
          </div>
          <div className="flex items-center justify-center gap-4 text-xs text-[#6b9e7e]">
            <span>Powered by Exponential.fi risk engine</span>
            <span>·</span>
            <a
              href="https://yo.xyz"
              target="_blank"
              rel="noopener noreferrer"
              className="text-[#22c55e] hover:text-[#16a34a] transition-colors"
            >
              Learn more →
            </a>
          </div>
        </div>
      </main>
    </>
  );
}
